AWSTemplateFormatVersion: "2010-09-09"
Description: "This Template Creates an EC2 instance in a defalut VPC"
Resources:
  myEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: apsouth1
      ImageId: ami-0ad704c126371a549
      InstanceType: t2.micro
      Monitoring: false
      UserData: !Base64 |
        #!/bin/bash -ex
        # put your script here
        yum update -y
        yum install httpd -y
        systemctl start httpd
        systemctl enable httpd
        echo "<h1> Hello From $(hostname -f)</h1>" > /var/www/html/index.html
      Tags:
        - Key: Name
          Value: EC2InstanceFromTemplate
